### PR TITLE
Update syna submodule to current master

### PR DESCRIPTION
**Pull request by xai**
This fixes a search-related issue, which is related to https://github.com/eclipse-glsp/glsp/issues/723.

### CODE REVIEW

**Review by planger — APPROVED** [review]
Thanks, looks good to me! :+1:

**Comment by planger** [comment]
Not sure why, but netlify didn't add a comment to print the link to the preview: https://deploy-preview-77--glsp.netlify.app/
@xai Is this already ok to merge? Thanks!

**Comment by xai** [comment]
> Not sure why, but netlify didn't add a comment to print the link to the preview: https://deploy-preview-77--glsp.netlify.app/ @xai Is this already ok to merge? Thanks!

Weird ... yes, it's good to merge. Then the search should work again.

**Comment by planger** [comment]
Maybe we are still missing some permissions for netlify so it can publish a comment that links to the preview. I'll ask at the EclipseFoundation.

**Pull request merged**
